joint_limits:
  elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.7
  forearm_roll_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.7
  left_gripper_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.7
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.7
  torso_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 0.2
  upperarm_roll_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.7
  wrist_flex_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.7
  wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.7
