// Generated by gencpp from file pose_cnn/Class.msg
// DO NOT EDIT!


#ifndef POSE_CNN_MESSAGE_CLASS_H
#define POSE_CNN_MESSAGE_CLASS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <pose_cnn/EachObject.h>

namespace pose_cnn
{
template <class ContainerAllocator>
struct Class_
{
  typedef Class_<ContainerAllocator> Type;

  Class_()
    : header()
    , objects()  {
    }
  Class_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::pose_cnn::EachObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pose_cnn::EachObject_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::pose_cnn::Class_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_cnn::Class_<ContainerAllocator> const> ConstPtr;

}; // struct Class_

typedef ::pose_cnn::Class_<std::allocator<void> > Class;

typedef boost::shared_ptr< ::pose_cnn::Class > ClassPtr;
typedef boost::shared_ptr< ::pose_cnn::Class const> ClassConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_cnn::Class_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_cnn::Class_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pose_cnn::Class_<ContainerAllocator1> & lhs, const ::pose_cnn::Class_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pose_cnn::Class_<ContainerAllocator1> & lhs, const ::pose_cnn::Class_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pose_cnn

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pose_cnn::Class_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_cnn::Class_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_cnn::Class_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_cnn::Class_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_cnn::Class_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_cnn::Class_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_cnn::Class_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f93a459fd733d74310fa2e7ea67cf95";
  }

  static const char* value(const ::pose_cnn::Class_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f93a459fd733d74ULL;
  static const uint64_t static_value2 = 0x310fa2e7ea67cf95ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_cnn::Class_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_cnn/Class";
  }

  static const char* value(const ::pose_cnn::Class_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_cnn::Class_<ContainerAllocator> >
{
  static const char* value()
  {
    return "###########################################################\n"
"# This message describes an object.\n"
"\n"
"# Many of the geometric items below lack a stamp/frame_id,\n"
"# header stamp/frame_id should be used there\n"
"std_msgs/Header header\n"
"\n"
"EachObject[] objects\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: pose_cnn/EachObject\n"
"###########################################################\n"
"# This message describes an object.\n"
"\n"
"# An object might have a name\n"
"string name\n"
"\n"
"# Poses of each object\n"
"geometry_msgs/PoseStamped posestamped\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pose_cnn::Class_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_cnn::Class_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Class_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_cnn::Class_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_cnn::Class_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pose_cnn::EachObject_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_CNN_MESSAGE_CLASS_H
