// Generated by gencpp from file pose_cnn/EachObject.msg
// DO NOT EDIT!


#ifndef POSE_CNN_MESSAGE_EACHOBJECT_H
#define POSE_CNN_MESSAGE_EACHOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace pose_cnn
{
template <class ContainerAllocator>
struct EachObject_
{
  typedef EachObject_<ContainerAllocator> Type;

  EachObject_()
    : name()
    , posestamped()  {
    }
  EachObject_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , posestamped(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _posestamped_type;
  _posestamped_type posestamped;





  typedef boost::shared_ptr< ::pose_cnn::EachObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_cnn::EachObject_<ContainerAllocator> const> ConstPtr;

}; // struct EachObject_

typedef ::pose_cnn::EachObject_<std::allocator<void> > EachObject;

typedef boost::shared_ptr< ::pose_cnn::EachObject > EachObjectPtr;
typedef boost::shared_ptr< ::pose_cnn::EachObject const> EachObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_cnn::EachObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_cnn::EachObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pose_cnn::EachObject_<ContainerAllocator1> & lhs, const ::pose_cnn::EachObject_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.posestamped == rhs.posestamped;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pose_cnn::EachObject_<ContainerAllocator1> & lhs, const ::pose_cnn::EachObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pose_cnn

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pose_cnn::EachObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_cnn::EachObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_cnn::EachObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_cnn::EachObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_cnn::EachObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_cnn::EachObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_cnn::EachObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81f443669f369cfa0946fd2ef8ca5011";
  }

  static const char* value(const ::pose_cnn::EachObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81f443669f369cfaULL;
  static const uint64_t static_value2 = 0x0946fd2ef8ca5011ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_cnn::EachObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_cnn/EachObject";
  }

  static const char* value(const ::pose_cnn::EachObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_cnn::EachObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "###########################################################\n"
"# This message describes an object.\n"
"\n"
"# An object might have a name\n"
"string name\n"
"\n"
"# Poses of each object\n"
"geometry_msgs/PoseStamped posestamped\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pose_cnn::EachObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_cnn::EachObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.posestamped);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EachObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_cnn::EachObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_cnn::EachObject_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "posestamped: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.posestamped);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_CNN_MESSAGE_EACHOBJECT_H
